# Timestamp
string(TIMESTAMP BUILD_DATE "%Y-%m-%d")
string(TIMESTAMP BUILD_TIME "%H:%M:%S")
set(BUILD_TIMESTAMP "${BUILD_DATE}-${BUILD_TIME}")

# Main executable version
set(CNCSIMU_VERSION_MAJOR 1)
set(CNCSIMU_VERSION_MINOR 0)
set(CNCSIMU_VERSION_PATCH 1)
set(CNCSIMU_VERSION "${CNCSIMU_VERSION_MAJOR}.${CNCSIMU_VERSION_MINOR}.${CNCSIMU_VERSION_PATCH}")

# Libs version
set(MILL_VERSION_MAJOR 1)
set(MILL_VERSION_MINOR 0)
set(MILL_VERSION_PATCH 2)
set(MILL_VERSION "${MILL_VERSION_MAJOR}.${MILL_VERSION_MINOR}.${MILL_VERSION_PATCH}")

set(TOOL_VERSION_MAJOR 1)
set(TOOL_VERSION_MINOR 0)
set(TOOL_VERSION_PATCH 1)
set(TOOL_VERSION "${TOOL_VERSION_MAJOR}.${TOOL_VERSION_MINOR}.${TOOL_VERSION_PATCH}")

set(LINUXCNC_VERSION 2.9.4)

# Git集成 (可选)
find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${CMAKE_SOURCE_DIR}/.git")
    execute_process(
        COMMAND git rev-parse --short HEAD
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE GIT_COMMIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    set(BUILD_VERSION_SUFFIX "+g${GIT_COMMIT_HASH}")
else()
    set(BUILD_VERSION_SUFFIX "")
endif()