/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/********************************************************************
* Description: config.h
*
*	Common defines used in many emc2 source files.
*       To add to this file, edit Section 4.1 in configure.ac
*       and then run autoheader.
*
* Author: Autogenerated by autoheader
* License: LGPL Version 2
* System: Linux
*
* Copyright (c) 2004 All rights reserved.
********************************************************************/
#ifndef EMC2_CONFIG_H
#define EMC2_CONFIG_H


/* Directory for binaries */
#define EMC2_BIN_DIR "/home/user/srcCode/linuxcnc-master/bin"

/* Default nml file */
#define EMC2_DEFAULT_NMLFILE "/home/user/srcCode/linuxcnc-master/configs/common/linuxcnc.nml"

/* Default nml file */
#define EMC2_DEFAULT_TOOLTABLE "/home/user/srcCode/linuxcnc-master/configs/sim/sim.tbl"

/* Directory for help files */
#define EMC2_HELP_DIR "/home/user/srcCode/linuxcnc-master/docs/help"

/* Prefix or RIP directory */
#define EMC2_HOME "/home/user/srcCode/linuxcnc-master"

/* Directory for images */
#define EMC2_IMAGE_DIR "/home/user/srcCode/linuxcnc-master"

/* Directory for tcl translation files */
#define EMC2_LANG_DIR "/home/user/srcCode/linuxcnc-master/src/objects"

/* Directory for nc files */
#define EMC2_NCFILES_DIR "/home/user/srcCode/linuxcnc-master/nc_files"

/* Directory for po/mo translation files */
#define EMC2_PO_DIR "/home/user/srcCode/linuxcnc-master/share/locale"

/* Directory of realtime system */
#define EMC2_RTLIB_DIR "/home/user/srcCode/linuxcnc-master/rtlib"

/* Directory for tcl scripts */
#define EMC2_TCL_DIR "/home/user/srcCode/linuxcnc-master/tcl"

/* Temporary files directory */
#define EMC2_TMP_DIR "/tmp/linuxcnc"

/* define if the Boost library is available */
#define HAVE_BOOST /**/

/* define if the Boost::Python library is available */
#define HAVE_BOOST_PYTHON /**/

/* Define to 1 if clock_nanosleep is available (in -lc or -lrt) */
#define HAVE_CLOCK_NANOSLEEP 1

/* define if the compiler supports basic C++20 syntax */
#define HAVE_CXX20 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `intl' library (-lintl). */
/* #undef HAVE_LIBINTL */

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* define if the libmodbus3 headers and library are available */
#define HAVE_LIBMODBUS3 yes

/* Define to 1 if you have the `tirpc' library (-ltirpc). */
#define HAVE_LIBTIRPC 1

/* define if the libusb-1.0 headers and library are available */
#define HAVE_LIBUSB10 yes

/* Define to 1 if you have the `Xinerama' library (-lXinerama). */
#define HAVE_LIBXINERAMA 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if getopt has the BSD 'optreset' extension */
/* #undef HAVE_OPTRESET */

/* If available, contains the Python version number currently in use. */
#define HAVE_PYTHON "3.11"

/* Define to 1 if you have the 'readline' library (-lreadline) and required
   headers */
#define HAVE_READLINE /**/

/* Define to 1 if you have the <readline/history.h> header file. */
#define HAVE_READLINE_HISTORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
#define HAVE_READLINE_READLINE_H 1

/* Define to 1 if you have the `semtimedop' function. */
#define HAVE_SEMTIMEDOP 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/io.h> header file. */
#define HAVE_SYS_IO_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <tcl.h> header file. */
/* #undef HAVE_TCL_H */

/* Define to 1 if you have the <tk.h> header file. */
/* #undef HAVE_TK_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <X11/extensions/Xinerama.h> header file. */
#define HAVE_X11_EXTENSIONS_XINERAMA_H 1

/* Define to 1 if you have the <X11/Xmu/Xmu.h> header file. */
#define HAVE_X11_XMU_XMU_H 1

/* Define to 1 if linux/hidraw.h is usable and defines HIDIOCGRAWINFO */
#define HIDRAW_H_USABLE /**/

/* Define to the library that dlopen comes from, if it is not a part of libc
   */
#define LIBDL $LIBDL

/* libgpiod version, undefined if not present */
/* #undef LIBGPIOD_VER */

/* Extension for realtime modules */
#define MODULE_EXT ".so"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "emc-developers@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "LinuxCNC"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "LinuxCNC 2.10.0~pre0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "linuxcnc"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.10.0~pre0"

/* Required kernel version */
/* #undef RTAPI_KERNEL_VERSION */

/* Realtime system is RTAI */
/* #undef RTAPI_RTAI */

/* Realtime system is userspace */
#define RTAPI_USPACE /**/

/* Directory of the installed realtime system */
#define RTDIR "/home/user/srcCode/linuxcnc-master/src"

/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Define if uspace realtime should optionally support RTAI LXRT */
/* #undef USPACE_RTAI */

/* Define if uspace realtime should optionally support Xenomai */
/* #undef USPACE_XENOMAI */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif


#endif

